version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '${PORT}:${PORT}'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PORT=${PORT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    ports:
      - '5432:5432'
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  data-portal:
    container_name: data-portal
    image: adminer
    ports:
      - 5000:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: hever
