name: Continuous Deployment

on:
  workflow_run:
    workflows:
      - Continuous Integration # Triggered after CI is complete
    types:
      - completed
env:
  ECR_IMAGE: ${{vars.ECR_IMAGE}} 
  AWS_REGION: ${{vars.AWS_REGION}}

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        # Checkout code
        - name: Checkout code
          uses: actions/checkout@v3

        # Configure AWS credentials
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: $AWS_REGION

        # Login to Amazon ECR
        - name: Login to Amazon ECR
          run: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

        # Build and push Docker image
        - name: Build and push Docker image
          run: |
            docker buildx create --use
            docker buildx inspect --bootstrap
            docker buildx build --platform linux/amd64 -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_IMAGE:latest --push .
