name: Continuous Integration

on:
  pull_request:
    branches:
      - 'main' # Run CI on pull requests to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run linting
      - name: Run lint
        run: pnpm run lint

      # Run tests
      - name: Run tests
        env:
          NODE_ENV: test
        run: pnpm run test
